### ISSUE TITLE
How Can I Change Variable Value  within the Property Get Block ? 

### ISSUE THREAD

**Issue by ismailkocacan** [punitganshani/CodeInject#1]
```
public class MyClass
{
    public int MyProperty 
    { 

        get
        {
            int x = 5;

            // how to change here
            return x;
        } 

    }
}


public class Application
{
    public static void main(String[] args)
    {
        MyClass myClass = new MyClass();

        int v = myClass.MyProperty;

    }
}
```

**Comment by punitganshani** [comment]
As of today, injection for getter and setter is not allowed

**Comment by ismailkocacan** [comment]
why not ?

**Comment by ismailkocacan** [comment]
or is there an alternative method ?

**Comment by ismailkocacan** [comment]
I will use for that http://stackoverflow.com/questions/28562358/how-can-i-modify-property-get-method-of-x509certificate2s-privatekey

**Comment by punitganshani** [comment]
You can try out v1.4.1 for injection to Getter Method

https://github.com/punitganshani/CodeInject/releases/tag/1.4.1

Let me know if that works for you. thanks

**Comment by ismailkocacan** [comment]
thanks for quickly reply :)
I will try

**Comment by ismailkocacan** [comment]
Now I'm trying to experiment with a simple example.
How do I access the variable x ?
Is there an example ?

**Comment by punitganshani** [comment]
There are few examples: 
https://github.com/punitganshani/CodeInject/wiki 
or https://www.ganshani.com/blog/2011/09/using-injectors-with-cinject/

**Comment by ismailkocacan** [comment]
I read them all :)

**Comment by ismailkocacan** [comment]
Can you give us an idea of how we can do ?

**Comment by ismailkocacan** [comment]
Can you seen that snippet ?
http://i.giphy.com/ytwDCBIFU48PIKCJ5C.gif

**Comment by punitganshani** [comment]
You don't have to change that.  Not sure if you understood how it works  

All you need to do is inherit ICInject interface.  You will get the value of injected method in the OnInvoke method.  

Something like 
- https://www.ganshani.com/blog/2011/09/cinject-quick-guide/ 
  and once you have an injector you could use it as mentioned in 
- http://www.ganshani.com/2011/09/28/using-injectors-with-cinject/

In your injector OnInvoke method, you can use reflection to change the value of property

**Comment by ismailkocacan** [comment]
I have a that  target class in my MyTarget.dll 

<pre><code class='language-cs'>
namespace MyTarget
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    public class MyClass
    {
        public int MyProperty 
        { 
            get
            {
                int x = 50;
                return x;
            } 
        }
    }
}
</code></pre>

My ICInject implemented class

<pre><code class='language-cs'>
namespace InjectorLib
{
    using CInject.Injections.Interfaces;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    public class MyGetPropertyInjector : ICInject
    {
        public void OnComplete()
        {
            
        }
        public void OnInvoke(CInject.Injections.Library.CInjection injection)
        {
            var propertyValues = injection.GetPropertyValue("MyProperty");
            // how to access x variable in that MyProperty get method ?
        }
        public void Dispose()
        {
            
        }
    }
}
</code></pre>

**Comment by punitganshani** [comment]
Sorry that's a valid use-case for CodeInject.  You can't find out variables inside a method.

**Comment by ismailkocacan** [comment]
thanks :+1:
