### ISSUE TITLE
WPF Window Closing event injection issue v1.4.1

### ISSUE THREAD

**Issue by mlhnet** [punitganshani/CodeInject#2]
Inject to a WPF application Closing event creates a corrupt injection.

it appears the OnComplete code was inserted in the wrong location which may have caused the corruption on the Window_OnClosing event method. Here is a insertion that does not crash however the OnComplete is in the wrong location.

Removing the insertion of the OnComplete method prevented the corruption of the Closing method.

This might help:

private void MainWindow_Loaded(object sender, RoutedEventArgs e)
 {
 LogInject logInject = new LogInject();
 CInjection cInjection = new CInjection()
 {
 Method = MethodBase.GetCurrentMethod(),
 ExecutingAssembly = Assembly.GetExecutingAssembly()
 };
 object[] objArray = new object[] { sender, e };
 cInjection.Arguments = objArray;
 logInject.OnInvoke(cInjection);
 -->// ORIG code starts here
 if (Settings.Default.ShowTutorial)
 {
 if (this._tutorialWindow == null)
 {
 this._tutorialWindow = new TutorialWindow()
 {
 Topmost = true
 };
 }
 this._tutorialWindow.Show();
 }
 string[] commandLineArgs = Environment.GetCommandLineArgs();
 if ((int)commandLineArgs.Length > 1)
 {
 string str = commandLineArgs[1];
 if (Path.GetExtension(str) == ".xyz")
 {
 --> // WHY WAS THIS INSERTED HERE!
 logInject.OnComplete();
 this.ShowProfileWindow(str);
 }
 }
 }

**Comment by mlhnet** [comment]
it appears the OnComplete code was inserted in the wrong location which may have caused the corruption on the Window_OnClosing event method. Here is a insertion that does not crash however the OnComplete is in the wrong location.
 
This might help:

 private void MainWindow_Loaded(object sender, RoutedEventArgs e)
        {
            LogInject logInject = new LogInject();
            CInjection cInjection = new CInjection()
            {
                Method = MethodBase.GetCurrentMethod(),
                ExecutingAssembly = Assembly.GetExecutingAssembly()
            };
            object[] objArray = new object[] { sender, e };
            cInjection.Arguments = objArray;
            logInject.OnInvoke(cInjection);
-->// ORIG code starts here
            if (Settings.Default.ShowTutorial)
            {
                if (this._tutorialWindow == null)
                {
                    this._tutorialWindow = new TutorialWindow()
                    {
                        Topmost = true
                    };
                }
                this._tutorialWindow.Show();
            }
            string[] commandLineArgs = Environment.GetCommandLineArgs();
            if ((int)commandLineArgs.Length > 1)
            {
                string str = commandLineArgs[1];
                if (Path.GetExtension(str) == ".xyz")
                {
--> // WHY WAS THIS INSERTED HERE!
                    logInject.OnComplete();
                    this.ShowProfileWindow(str);
                }
            }
        }

**Comment by punitganshani** [comment]
Is it possible to paste the code using markdown tag so that its readable using ```

**Comment by punitganshani** [comment]
I tried replicating this with a sample WPF application but could not find any issue.  
I've added the WPF sample application with commit 02f7daac62c6645e944fe418f1d5c7394c804a63
