### ISSUE TITLE
Support for .NET higher than 4.0

### ISSUE THREAD

**Issue by yazido** [punitganshani/CodeInject#4]
Hello Punit,
I would ask you if it's planed to support .NET higher than 4.0 in next releases?

thank you in advance,
Yazi

**Comment by Tybielee** [comment]
This is also something I would also like to see.

**Comment by punitganshani** [comment]
Yes that is planned.

I'm evaluating on the approach to allow injection in newer versions of .NET

**Comment by Tybielee** [comment]
@punitganshani That is great to hear! Do you have any sort of rough timeline on it?

**Comment by punitganshani** [comment]
@Tybielee @yazido this is fixed in 4d908e5932b8463a8c87dd13b6c4b61657b6f8e1

Release Version: 1.5
