### ISSUE TITLE
In LogInject string parameters cannot be dumped

### ISSUE THREAD

**Issue by AndrewSav** [punitganshani/CodeInject#5]
Since a string is also an `IEnumerable`of chars, that's what CodeInject assumes and splits all strings as characters, and not just as characters, as their numerical values, which is rarely useful.

It would be better if LogInject could dump string parameters as is.

**Comment by punitganshani** [comment]
Checked- this will be fixed soon

**Comment by punitganshani** [comment]
@AndrewSav This has been fixed in Release v 1.5
